// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_links.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteApiLinkByUserAndName = `-- name: DeleteApiLinkByUserAndName :exec
DELETE FROM api_links
WHERE user_id = $1 AND name = $2
`

type DeleteApiLinkByUserAndNameParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) DeleteApiLinkByUserAndName(ctx context.Context, arg DeleteApiLinkByUserAndNameParams) error {
	_, err := q.db.Exec(ctx, deleteApiLinkByUserAndName, arg.UserID, arg.Name)
	return err
}

const getApiLinkByUserAndName = `-- name: GetApiLinkByUserAndName :one
SELECT id, user_id, name, refresh_token, refresh_token_iv, created_at, updated_at, key_id FROM api_links
WHERE user_id = $1 AND name = $2
`

type GetApiLinkByUserAndNameParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) GetApiLinkByUserAndName(ctx context.Context, arg GetApiLinkByUserAndNameParams) (ApiLink, error) {
	row := q.db.QueryRow(ctx, getApiLinkByUserAndName, arg.UserID, arg.Name)
	var i ApiLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RefreshToken,
		&i.RefreshTokenIv,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyID,
	)
	return i, err
}

const getApiLinkByUserAndNameForUpdate = `-- name: GetApiLinkByUserAndNameForUpdate :one
SELECT id, user_id, name, refresh_token, refresh_token_iv, created_at, updated_at, key_id FROM api_links
WHERE user_id = $1 AND name = $2
FOR UPDATE
`

type GetApiLinkByUserAndNameForUpdateParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) GetApiLinkByUserAndNameForUpdate(ctx context.Context, arg GetApiLinkByUserAndNameForUpdateParams) (ApiLink, error) {
	row := q.db.QueryRow(ctx, getApiLinkByUserAndNameForUpdate, arg.UserID, arg.Name)
	var i ApiLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RefreshToken,
		&i.RefreshTokenIv,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyID,
	)
	return i, err
}

const upsertApiLink = `-- name: UpsertApiLink :one
INSERT INTO api_links (id, user_id, name, refresh_token, refresh_token_iv, key_id, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
ON CONFLICT (user_id, name)
DO UPDATE SET
    refresh_token = EXCLUDED.refresh_token,
    refresh_token_iv = EXCLUDED.refresh_token_iv,
    key_id = EXCLUDED.key_id,
    updated_at = NOW()
RETURNING id, user_id, name, refresh_token, refresh_token_iv, created_at, updated_at, key_id
`

type UpsertApiLinkParams struct {
	UserID         uuid.UUID
	Name           string
	RefreshToken   string
	RefreshTokenIv string
	KeyID          string
}

func (q *Queries) UpsertApiLink(ctx context.Context, arg UpsertApiLinkParams) (ApiLink, error) {
	row := q.db.QueryRow(ctx, upsertApiLink,
		arg.UserID,
		arg.Name,
		arg.RefreshToken,
		arg.RefreshTokenIv,
		arg.KeyID,
	)
	var i ApiLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RefreshToken,
		&i.RefreshTokenIv,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyID,
	)
	return i, err
}
