// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLobbiesByGroupId = `-- name: CountLobbiesByGroupId :one
SELECT COUNT(*)::INT
FROM lobbies AS L
JOIN events AS E ON E.id = L.event_id
WHERE E.group_id = $1
`

func (q *Queries) CountLobbiesByGroupId(ctx context.Context, groupID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countLobbiesByGroupId, groupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, group_id, start_time, game_mode_id, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    NOW()
)
`

type CreateEventParams struct {
	GroupID    *uuid.UUID
	StartTime  time.Time
	GameModeID uuid.UUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent, arg.GroupID, arg.StartTime, arg.GameModeID)
	return err
}

const createEventGroup = `-- name: CreateEventGroup :one
INSERT INTO event_groups (id, owner_id, sub_min, registration_open, region, sort_logic, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
RETURNING id, owner_id, sub_min, registration_open, is_public, deprioritize_noshows, max_noshows, discord_guild, region, created_at, updated_at, sort_logic
`

type CreateEventGroupParams struct {
	OwnerID          uuid.UUID
	SubMin           int32
	RegistrationOpen bool
	Region           string
	SortLogic        string
}

func (q *Queries) CreateEventGroup(ctx context.Context, arg CreateEventGroupParams) (EventGroup, error) {
	row := q.db.QueryRow(ctx, createEventGroup,
		arg.OwnerID,
		arg.SubMin,
		arg.RegistrationOpen,
		arg.Region,
		arg.SortLogic,
	)
	var i EventGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SubMin,
		&i.RegistrationOpen,
		&i.IsPublic,
		&i.DeprioritizeNoshows,
		&i.MaxNoshows,
		&i.DiscordGuild,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortLogic,
	)
	return i, err
}

const createLobby = `-- name: CreateLobby :one
INSERT INTO lobbies (id, event_id, host, fairness_warning, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, NOW(), NOW())
RETURNING id, event_id, host, created_at, updated_at, fairness_warning
`

type CreateLobbyParams struct {
	EventID         *uuid.UUID
	Host            *uuid.UUID
	FairnessWarning bool
}

func (q *Queries) CreateLobby(ctx context.Context, arg CreateLobbyParams) (Lobby, error) {
	row := q.db.QueryRow(ctx, createLobby, arg.EventID, arg.Host, arg.FairnessWarning)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Host,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FairnessWarning,
	)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :exec
INSERT INTO players (lobby_id, user_id, team_number, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
`

type CreatePlayerParams struct {
	LobbyID    uuid.UUID
	UserID     uuid.UUID
	TeamNumber *int32
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) error {
	_, err := q.db.Exec(ctx, createPlayer, arg.LobbyID, arg.UserID, arg.TeamNumber)
	return err
}

const deleteEventGroupById = `-- name: DeleteEventGroupById :execrows
DELETE FROM event_groups
WHERE id = $1
`

func (q *Queries) DeleteEventGroupById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventGroupById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLobbiesByGroupId = `-- name: DeleteLobbiesByGroupId :exec
DELETE FROM lobbies
WHERE event_id IN (
    SELECT id
    FROM events
    WHERE group_id = $1
)
`

func (q *Queries) DeleteLobbiesByGroupId(ctx context.Context, groupID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLobbiesByGroupId, groupID)
	return err
}

const deletePlayersByGroupId = `-- name: DeletePlayersByGroupId :exec
DELETE FROM players
WHERE lobby_id IN (
    SELECT L.id
    FROM lobbies AS L
    JOIN events AS E ON E.id = L.event_id
    WHERE E.group_id = $1
)
`

func (q *Queries) DeletePlayersByGroupId(ctx context.Context, groupID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlayersByGroupId, groupID)
	return err
}

const getEventGroupById = `-- name: GetEventGroupById :one
SELECT id, owner_id, sub_min, registration_open, is_public, deprioritize_noshows, max_noshows, discord_guild, region, created_at, updated_at, sort_logic FROM event_groups WHERE id = $1
`

func (q *Queries) GetEventGroupById(ctx context.Context, id uuid.UUID) (EventGroup, error) {
	row := q.db.QueryRow(ctx, getEventGroupById, id)
	var i EventGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SubMin,
		&i.RegistrationOpen,
		&i.IsPublic,
		&i.DeprioritizeNoshows,
		&i.MaxNoshows,
		&i.DiscordGuild,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortLogic,
	)
	return i, err
}

const getEventGroupDetailById = `-- name: GetEventGroupDetailById :one
SELECT
    EG.id,
    EG.owner_id,
    COALESCE(U.discord_name, '') AS owner_name,
    CAST(
        CASE
            WHEN U.show_pronouns = TRUE THEN COALESCE(U.pronouns, '')
            ELSE ''
        END
        AS TEXT
    ) AS owner_pronouns,
    CAST(COALESCE(
        (SELECT STRING_AGG(DISTINCT gm_agg.name, ', ' ORDER BY gm_agg.name)
         FROM events E_agg
         JOIN game_modes gm_agg ON gm_agg.id = E_agg.game_mode_id
         WHERE E_agg.group_id = EG.id),
        ''
    ) AS VARCHAR(4096)) AS game_mode_name,
    CAST(
        CASE
            WHEN (SELECT COUNT(DISTINCT E_mid.game_mode_id) FROM events E_mid WHERE E_mid.group_id = EG.id) = 1
            THEN (SELECT E_mid.game_mode_id FROM events E_mid WHERE E_mid.group_id = EG.id LIMIT 1)
            ELSE '00000000-0000-0000-0000-000000000000'::uuid
        END
        AS UUID
    ) AS game_mode_id,
    CAST(
        COALESCE(
            (SELECT G_first.id
             FROM events E_first
             JOIN game_modes GM_first ON GM_first.id = E_first.game_mode_id
             JOIN games G_first ON G_first.id = GM_first.game_id
             WHERE E_first.group_id = EG.id
             ORDER BY E_first.start_time ASC NULLS LAST
             LIMIT 1),
            '00000000-0000-0000-0000-000000000000'::uuid
        )
        AS UUID
    ) AS game_id,
    CAST(
        COALESCE(
            (SELECT G_first.name
             FROM events E_first
             JOIN game_modes GM_first ON GM_first.id = E_first.game_mode_id
             JOIN games G_first ON G_first.id = GM_first.game_id
             WHERE E_first.group_id = EG.id
             ORDER BY E_first.start_time ASC NULLS LAST
             LIMIT 1),
            ''
        )
        AS TEXT
    ) AS game_name,
    CAST(
        CASE
            WHEN (SELECT COUNT(DISTINCT GM_sz.team_size) FROM events E_sz JOIN game_modes GM_sz ON GM_sz.id = E_sz.game_mode_id WHERE E_sz.group_id = EG.id) = 1
            THEN (SELECT MIN(GM_sz.team_size) FROM events E_sz JOIN game_modes GM_sz ON GM_sz.id = E_sz.game_mode_id WHERE E_sz.group_id = EG.id)
            ELSE 0
        END
        AS INT
    ) AS team_size,
    EG.sub_min,
    EG.registration_open,
    EG.region,
    EG.sort_logic,
    EG.created_at,
    EG.updated_at
FROM event_groups AS EG
JOIN users AS U ON U.id = EG.owner_id
WHERE EG.id = $1
`

type GetEventGroupDetailByIdRow struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	OwnerName        string
	OwnerPronouns    string
	GameModeName     string
	GameModeID       uuid.UUID
	GameID           uuid.UUID
	GameName         string
	TeamSize         int32
	SubMin           int32
	RegistrationOpen bool
	Region           string
	SortLogic        string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetEventGroupDetailById(ctx context.Context, id uuid.UUID) (GetEventGroupDetailByIdRow, error) {
	row := q.db.QueryRow(ctx, getEventGroupDetailById, id)
	var i GetEventGroupDetailByIdRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OwnerName,
		&i.OwnerPronouns,
		&i.GameModeName,
		&i.GameModeID,
		&i.GameID,
		&i.GameName,
		&i.TeamSize,
		&i.SubMin,
		&i.RegistrationOpen,
		&i.Region,
		&i.SortLogic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventWithGroupById = `-- name: GetEventWithGroupById :one
SELECT
    E.id,
    E.group_id,
    G.id AS game_id,
    EG.owner_id,
    EG.registration_open
FROM events AS E
JOIN event_groups AS EG ON EG.id = E.group_id
JOIN game_modes AS GM ON GM.id = E.game_mode_id
JOIN games AS G ON G.id = GM.game_id
WHERE E.id = $1
`

type GetEventWithGroupByIdRow struct {
	ID               uuid.UUID
	GroupID          *uuid.UUID
	GameID           uuid.UUID
	OwnerID          uuid.UUID
	RegistrationOpen bool
}

func (q *Queries) GetEventWithGroupById(ctx context.Context, id uuid.UUID) (GetEventWithGroupByIdRow, error) {
	row := q.db.QueryRow(ctx, getEventWithGroupById, id)
	var i GetEventWithGroupByIdRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.GameID,
		&i.OwnerID,
		&i.RegistrationOpen,
	)
	return i, err
}

const getEventsByGroupId = `-- name: GetEventsByGroupId :many
SELECT id, group_id, start_time, created_at, updated_at, game_mode_id FROM events WHERE group_id = $1 ORDER BY start_time ASC
`

func (q *Queries) GetEventsByGroupId(ctx context.Context, groupID *uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByGroupId, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.StartTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GameModeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsForUser = `-- name: GetEventsForUser :many
WITH grouped AS (
    SELECT
        EG.id AS id,
        G.name AS game_name,
        CAST(STRING_AGG(DISTINCT GM.name, ', ' ORDER BY GM.name) AS VARCHAR(4096)) AS game_mode,
        MIN(E.start_time)::TIMESTAMPTZ AS event_date,
        H.id AS host_id,
        COALESCE(H.discord_name, '') AS host_name,
        COUNT(DISTINCT RA.user_id)::INT AS registered_count,
        EG.registration_open
    FROM events AS E
    JOIN event_groups AS EG ON EG.id = E.group_id
    JOIN game_modes AS GM ON GM.id = E.game_mode_id
    JOIN games AS G ON G.id = GM.game_id
    JOIN users AS H ON H.id = EG.owner_id
    LEFT JOIN registrations AS RA ON RA.event_id = E.id
    WHERE
        (
            ($5::BOOL = TRUE AND EG.owner_id = $6)
            OR
            ($5::BOOL = FALSE AND EXISTS (
                SELECT 1
                FROM events AS ER
                JOIN registrations AS RM ON RM.event_id = ER.id
                WHERE ER.group_id = EG.id AND RM.user_id = $6
            ))
        )
        AND (NOT $7::BOOL OR (CASE WHEN $8::BOOL THEN E.start_time < $9::TIMESTAMPTZ ELSE E.start_time >= $9::TIMESTAMPTZ END))
        AND (NOT $10::BOOL OR E.start_time >= $11::TIMESTAMPTZ)
        AND (NOT $12::BOOL OR E.start_time < $13::TIMESTAMPTZ)
        AND (NOT $14::BOOL OR G.id = $15::UUID)
    GROUP BY EG.id, G.name, H.id, H.discord_name, EG.registration_open
)
SELECT id, game_name, game_mode, event_date, host_id, host_name, registered_count, registration_open
FROM grouped
WHERE (NOT $1::BOOL OR (event_date, id) > ($2::TIMESTAMPTZ, $3::UUID))
ORDER BY event_date ASC, id ASC
LIMIT $4::INT
`

type GetEventsForUserParams struct {
	HasCursor       bool
	CursorTime      time.Time
	CursorID        uuid.UUID
	LimitCount      int32
	Hosting         bool
	UserID          uuid.UUID
	ApplyPastFilter bool
	Past            bool
	BoundaryTime    time.Time
	HasFrom         bool
	FromTime        time.Time
	HasTo           bool
	ToTime          time.Time
	HasGameID       bool
	GameID          uuid.UUID
}

type GetEventsForUserRow struct {
	ID               uuid.UUID
	GameName         string
	GameMode         string
	EventDate        time.Time
	HostID           uuid.UUID
	HostName         string
	RegisteredCount  int32
	RegistrationOpen bool
}

func (q *Queries) GetEventsForUser(ctx context.Context, arg GetEventsForUserParams) ([]GetEventsForUserRow, error) {
	rows, err := q.db.Query(ctx, getEventsForUser,
		arg.HasCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.LimitCount,
		arg.Hosting,
		arg.UserID,
		arg.ApplyPastFilter,
		arg.Past,
		arg.BoundaryTime,
		arg.HasFrom,
		arg.FromTime,
		arg.HasTo,
		arg.ToTime,
		arg.HasGameID,
		arg.GameID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsForUserRow
	for rows.Next() {
		var i GetEventsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GameName,
			&i.GameMode,
			&i.EventDate,
			&i.HostID,
			&i.HostName,
			&i.RegisteredCount,
			&i.RegistrationOpen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupEventsSummary = `-- name: GetGroupEventsSummary :many
SELECT
    E.id,
    E.start_time,
    E.game_mode_id,
    GM.name AS game_mode_name,
    GM.team_size,
    COUNT(DISTINCT R.user_id)::INT AS registered_count,
    COUNT(DISTINCT L.id)::INT AS lobbies_count,
    COALESCE(BOOL_OR(R.user_id = $2), FALSE)::BOOL AS player_registered
FROM events AS E
JOIN game_modes AS GM ON GM.id = E.game_mode_id
LEFT JOIN registrations AS R ON R.event_id = E.id
LEFT JOIN lobbies AS L ON L.event_id = E.id
WHERE E.group_id = $1
GROUP BY E.id, E.start_time, E.game_mode_id, GM.name, GM.team_size
ORDER BY E.start_time ASC
`

type GetGroupEventsSummaryParams struct {
	GroupID  *uuid.UUID
	ViewerID uuid.UUID
}

type GetGroupEventsSummaryRow struct {
	ID               uuid.UUID
	StartTime        time.Time
	GameModeID       uuid.UUID
	GameModeName     string
	TeamSize         int32
	RegisteredCount  int32
	LobbiesCount     int32
	PlayerRegistered bool
}

func (q *Queries) GetGroupEventsSummary(ctx context.Context, arg GetGroupEventsSummaryParams) ([]GetGroupEventsSummaryRow, error) {
	rows, err := q.db.Query(ctx, getGroupEventsSummary, arg.GroupID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupEventsSummaryRow
	for rows.Next() {
		var i GetGroupEventsSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.GameModeID,
			&i.GameModeName,
			&i.TeamSize,
			&i.RegisteredCount,
			&i.LobbiesCount,
			&i.PlayerRegistered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLobbiesForEvent = `-- name: GetLobbiesForEvent :many
SELECT id, event_id, host, fairness_warning
FROM lobbies
WHERE event_id = $1
ORDER BY created_at ASC
`

type GetLobbiesForEventRow struct {
	ID              uuid.UUID
	EventID         *uuid.UUID
	Host            *uuid.UUID
	FairnessWarning bool
}

func (q *Queries) GetLobbiesForEvent(ctx context.Context, eventID *uuid.UUID) ([]GetLobbiesForEventRow, error) {
	rows, err := q.db.Query(ctx, getLobbiesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLobbiesForEventRow
	for rows.Next() {
		var i GetLobbiesForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Host,
			&i.FairnessWarning,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersForLobby = `-- name: GetPlayersForLobby :many
SELECT P.user_id,
       P.team_number,
       U.discord_name,
       CASE
           WHEN $1::BOOL = TRUE OR U.show_pronouns = true THEN COALESCE(U.pronouns, '')
           ELSE ''
       END AS pronouns,
       CASE
           WHEN $1::BOOL = TRUE OR COALESCE(UG.show_rank, FALSE) = TRUE THEN COALESCE(GR.name, '')
           ELSE ''
       END AS current_rank_name,
       CASE
           WHEN $1::BOOL = TRUE OR COALESCE(UG.show_rank, FALSE) = TRUE THEN COALESCE(GR."order", 0)
           ELSE 0
       END::INT AS current_rank_order,
       CASE
           WHEN $1::BOOL = TRUE OR COALESCE(UG.show_rank, FALSE) = TRUE THEN COALESCE(PR."order", 0)
           ELSE 0
       END::INT AS peak_rank_order,
       R.can_substitute,
       R.can_lobby_host,
       R.created_at,
       R.updated_at
FROM players AS P
JOIN users AS U ON U.id = P.user_id
JOIN lobbies AS L ON L.id = P.lobby_id
JOIN events AS E ON E.id = L.event_id
JOIN registrations AS R ON R.event_id = E.id AND R.user_id = P.user_id
JOIN game_modes AS GM ON GM.id = E.game_mode_id
LEFT JOIN user_games AS UG ON P.user_id = UG.user_id AND UG.game_id = GM.game_id
LEFT JOIN game_ranks AS GR ON UG.current_rank = GR.id
LEFT JOIN game_ranks AS PR ON UG.peak_rank = PR.id
WHERE P.lobby_id = $2
ORDER BY P.team_number ASC NULLS LAST, U.discord_name ASC
`

type GetPlayersForLobbyParams struct {
	ViewerIsHost bool
	LobbyID      uuid.UUID
}

type GetPlayersForLobbyRow struct {
	UserID           uuid.UUID
	TeamNumber       *int32
	DiscordName      *string
	Pronouns         string
	CurrentRankName  string
	CurrentRankOrder int32
	PeakRankOrder    int32
	CanSubstitute    bool
	CanLobbyHost     bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetPlayersForLobby(ctx context.Context, arg GetPlayersForLobbyParams) ([]GetPlayersForLobbyRow, error) {
	rows, err := q.db.Query(ctx, getPlayersForLobby, arg.ViewerIsHost, arg.LobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayersForLobbyRow
	for rows.Next() {
		var i GetPlayersForLobbyRow
		if err := rows.Scan(
			&i.UserID,
			&i.TeamNumber,
			&i.DiscordName,
			&i.Pronouns,
			&i.CurrentRankName,
			&i.CurrentRankOrder,
			&i.PeakRankOrder,
			&i.CanSubstitute,
			&i.CanLobbyHost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventGroupRegistrationOpen = `-- name: SetEventGroupRegistrationOpen :one
UPDATE event_groups
SET registration_open = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, sub_min, registration_open, is_public, deprioritize_noshows, max_noshows, discord_guild, region, created_at, updated_at, sort_logic
`

type SetEventGroupRegistrationOpenParams struct {
	ID               uuid.UUID
	RegistrationOpen bool
}

func (q *Queries) SetEventGroupRegistrationOpen(ctx context.Context, arg SetEventGroupRegistrationOpenParams) (EventGroup, error) {
	row := q.db.QueryRow(ctx, setEventGroupRegistrationOpen, arg.ID, arg.RegistrationOpen)
	var i EventGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SubMin,
		&i.RegistrationOpen,
		&i.IsPublic,
		&i.DeprioritizeNoshows,
		&i.MaxNoshows,
		&i.DiscordGuild,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortLogic,
	)
	return i, err
}

const updateEventGroupSettings = `-- name: UpdateEventGroupSettings :one
UPDATE event_groups
SET region = $2, sub_min = $3, sort_logic = $4, registration_open = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, sub_min, registration_open, is_public, deprioritize_noshows, max_noshows, discord_guild, region, created_at, updated_at, sort_logic
`

type UpdateEventGroupSettingsParams struct {
	ID               uuid.UUID
	Region           string
	SubMin           int32
	SortLogic        string
	RegistrationOpen bool
}

func (q *Queries) UpdateEventGroupSettings(ctx context.Context, arg UpdateEventGroupSettingsParams) (EventGroup, error) {
	row := q.db.QueryRow(ctx, updateEventGroupSettings,
		arg.ID,
		arg.Region,
		arg.SubMin,
		arg.SortLogic,
		arg.RegistrationOpen,
	)
	var i EventGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SubMin,
		&i.RegistrationOpen,
		&i.IsPublic,
		&i.DeprioritizeNoshows,
		&i.MaxNoshows,
		&i.DiscordGuild,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortLogic,
	)
	return i, err
}

const updateEventSchedule = `-- name: UpdateEventSchedule :execrows
UPDATE events
SET start_time = $2, game_mode_id = $3, updated_at = NOW()
WHERE id = $1 AND group_id = $4
`

type UpdateEventScheduleParams struct {
	ID         uuid.UUID
	StartTime  time.Time
	GameModeID uuid.UUID
	GroupID    *uuid.UUID
}

func (q *Queries) UpdateEventSchedule(ctx context.Context, arg UpdateEventScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventSchedule,
		arg.ID,
		arg.StartTime,
		arg.GameModeID,
		arg.GroupID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
