// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_group_discord_guilds.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteEventGroupDiscordGuildsByGroupID = `-- name: DeleteEventGroupDiscordGuildsByGroupID :exec
DELETE FROM event_group_discord_guilds
WHERE event_group_id = $1
`

func (q *Queries) DeleteEventGroupDiscordGuildsByGroupID(ctx context.Context, eventGroupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventGroupDiscordGuildsByGroupID, eventGroupID)
	return err
}

const insertEventGroupDiscordGuild = `-- name: InsertEventGroupDiscordGuild :one
INSERT INTO event_group_discord_guilds (
    id,
    event_group_id,
    guild_id,
    guild_name,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    NOW()
)
RETURNING id, created_at, updated_at, event_group_id, guild_id, guild_name
`

type InsertEventGroupDiscordGuildParams struct {
	EventGroupID uuid.UUID
	GuildID      string
	GuildName    string
}

func (q *Queries) InsertEventGroupDiscordGuild(ctx context.Context, arg InsertEventGroupDiscordGuildParams) (EventGroupDiscordGuild, error) {
	row := q.db.QueryRow(ctx, insertEventGroupDiscordGuild, arg.EventGroupID, arg.GuildID, arg.GuildName)
	var i EventGroupDiscordGuild
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventGroupID,
		&i.GuildID,
		&i.GuildName,
	)
	return i, err
}

const listEventGroupDiscordGuildsByGroupID = `-- name: ListEventGroupDiscordGuildsByGroupID :many
SELECT id, created_at, updated_at, event_group_id, guild_id, guild_name
FROM event_group_discord_guilds
WHERE event_group_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListEventGroupDiscordGuildsByGroupID(ctx context.Context, eventGroupID uuid.UUID) ([]EventGroupDiscordGuild, error) {
	rows, err := q.db.Query(ctx, listEventGroupDiscordGuildsByGroupID, eventGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventGroupDiscordGuild
	for rows.Next() {
		var i EventGroupDiscordGuild
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventGroupID,
			&i.GuildID,
			&i.GuildName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
