// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, group_id, start_time, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW()
)
`

type CreateEventParams struct {
	GroupID   *uuid.UUID
	StartTime time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent, arg.GroupID, arg.StartTime)
	return err
}

const createEventGroup = `-- name: CreateEventGroup :one
INSERT INTO event_groups (id, owner_id, game_mode_id, sub_min, registration_open, region, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
RETURNING id, owner_id, game_mode_id, sub_min, registration_open, is_public, deprioritize_noshows, max_noshows, discord_guild, region, created_at, updated_at
`

type CreateEventGroupParams struct {
	OwnerID          uuid.UUID
	GameModeID       uuid.UUID
	SubMin           int32
	RegistrationOpen bool
	Region           string
}

func (q *Queries) CreateEventGroup(ctx context.Context, arg CreateEventGroupParams) (EventGroup, error) {
	row := q.db.QueryRow(ctx, createEventGroup,
		arg.OwnerID,
		arg.GameModeID,
		arg.SubMin,
		arg.RegistrationOpen,
		arg.Region,
	)
	var i EventGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GameModeID,
		&i.SubMin,
		&i.RegistrationOpen,
		&i.IsPublic,
		&i.DeprioritizeNoshows,
		&i.MaxNoshows,
		&i.DiscordGuild,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
