// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package db

import (
	"context"
)

const getSystemGames = `-- name: GetSystemGames :many
SELECT id, name, owner_id, created_at, updated_at FROM games WHERE owner_id IS NULL
`

func (q *Queries) GetSystemGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, getSystemGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
