// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_ranks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getRankById = `-- name: GetRankById :one
SELECT id, game_id, name, "order", created_at, updated_at FROM game_ranks WHERE id = $1
`

func (q *Queries) GetRankById(ctx context.Context, id uuid.UUID) (GameRank, error) {
	row := q.db.QueryRow(ctx, getRankById, id)
	var i GameRank
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Name,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRanksForGame = `-- name: GetRanksForGame :many
SELECT id, game_id, name, "order", created_at, updated_at FROM game_ranks WHERE game_id = $1
`

func (q *Queries) GetRanksForGame(ctx context.Context, gameID *uuid.UUID) ([]GameRank, error) {
	rows, err := q.db.Query(ctx, getRanksForGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameRank
	for rows.Next() {
		var i GameRank
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Name,
			&i.Order,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
