// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type ApiLink struct {
	ID             uuid.UUID
	UserID         *uuid.UUID
	Name           *string
	RefreshToken   *string
	RefreshTokenIv *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Event struct {
	ID        uuid.UUID
	GroupID   *uuid.UUID
	StartTime **time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type EventGroup struct {
	ID                  uuid.UUID
	OwnerID             uuid.UUID
	GameModeID          uuid.UUID
	SubMin              int32
	RegistrationOpen    bool
	IsPublic            bool
	DeprioritizeNoshows bool
	MaxNoshows          int32
	DiscordGuild        *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Game struct {
	ID        uuid.UUID
	Name      string
	OwnerID   *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GameMode struct {
	ID        uuid.UUID
	GameID    uuid.UUID
	Name      string
	TeamSize  int32
	OwnerID   *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GameRank struct {
	ID        uuid.UUID
	GameID    *uuid.UUID
	Name      string
	Order     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Lobby struct {
	ID        uuid.UUID
	EventID   *uuid.UUID
	Host      *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Player struct {
	LobbyID    uuid.UUID
	UserID     uuid.UUID
	TeamNumber *int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt **time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Registration struct {
	EventID       uuid.UUID
	UserID        uuid.UUID
	CanSubstitute bool
	CanLobbyHost  bool
	DuoRequest    *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID           uuid.UUID
	DiscordID    *string
	DiscordName  *string
	ImageUrl     *string
	Pronouns     *string
	ShowPronouns bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Region       *string
	NewUser      bool
}

type UserGame struct {
	UserID        uuid.UUID
	GameID        uuid.UUID
	InGameName    string
	Region        *string
	CurrentRank   *uuid.UUID
	PeakRank      *uuid.UUID
	ShowRank      bool
	ApiPermission bool
	ApiLinksID    *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UserNoshow struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}
