// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiLink struct {
	ID             uuid.UUID
	UserID         *uuid.UUID
	Name           *string
	RefreshToken   *string
	RefreshTokenIv *string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Event struct {
	ID        uuid.UUID
	GroupID   *uuid.UUID
	StartTime pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type EventGroup struct {
	ID                  uuid.UUID
	OwnerID             uuid.UUID
	GameModeID          uuid.UUID
	SubMin              int32
	RegistrationOpen    bool
	IsPublic            bool
	DeprioritizeNoshows bool
	MaxNoshows          int32
	DiscordGuild        *string
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

type Game struct {
	ID        uuid.UUID
	Name      string
	OwnerID   *uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type GameMode struct {
	ID        uuid.UUID
	GameID    uuid.UUID
	Name      string
	TeamSize  int32
	OwnerID   *uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type GameRank struct {
	ID        uuid.UUID
	GameID    *uuid.UUID
	Name      string
	Order     int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Lobby struct {
	ID        uuid.UUID
	EventID   *uuid.UUID
	Host      *uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Player struct {
	LobbyID    uuid.UUID
	UserID     uuid.UUID
	TeamNumber *int32
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Registration struct {
	EventID       uuid.UUID
	UserID        uuid.UUID
	CanSubstitute bool
	CanLobbyHost  bool
	DuoRequest    *string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type User struct {
	ID           uuid.UUID
	DiscordID    *string
	DiscordName  *string
	ImageUrl     *string
	Pronouns     *string
	ShowPronouns bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type UserGame struct {
	UserID        uuid.UUID
	GameID        uuid.UUID
	InGameName    string
	Region        *string
	CurrentRank   *uuid.UUID
	PeakRank      *uuid.UUID
	ShowRank      bool
	ApiPermission bool
	ApiLinksID    *uuid.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type UserNoshow struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}
