// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: one_time_codes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const consumeOneTimeCode = `-- name: ConsumeOneTimeCode :one
DELETE FROM one_time_codes
WHERE code = $1 AND expires > now()
RETURNING user_id
`

func (q *Queries) ConsumeOneTimeCode(ctx context.Context, code string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeOneTimeCode, code)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createOneTimeCode = `-- name: CreateOneTimeCode :exec
INSERT INTO one_time_codes (code, user_id)
VALUES (
    $1,
    $2
)
`

type CreateOneTimeCodeParams struct {
	Code   string
	UserID uuid.UUID
}

func (q *Queries) CreateOneTimeCode(ctx context.Context, arg CreateOneTimeCodeParams) error {
	_, err := q.db.Exec(ctx, createOneTimeCode, arg.Code, arg.UserID)
	return err
}
