// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRegistration = `-- name: CreateRegistration :one
INSERT INTO registrations (event_id, user_id, can_substitute, can_lobby_host, duo_request, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING event_id, user_id, can_substitute, can_lobby_host, duo_request, created_at, updated_at
`

type CreateRegistrationParams struct {
	EventID       uuid.UUID
	UserID        uuid.UUID
	CanSubstitute bool
	CanLobbyHost  bool
	DuoRequest    *string
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) (Registration, error) {
	row := q.db.QueryRow(ctx, createRegistration,
		arg.EventID,
		arg.UserID,
		arg.CanSubstitute,
		arg.CanLobbyHost,
		arg.DuoRequest,
	)
	var i Registration
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.CanSubstitute,
		&i.CanLobbyHost,
		&i.DuoRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRegistration = `-- name: DeleteRegistration :exec
DELETE FROM registrations
WHERE event_id = $1 AND user_id = $2
`

type DeleteRegistrationParams struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteRegistration(ctx context.Context, arg DeleteRegistrationParams) error {
	_, err := q.db.Exec(ctx, deleteRegistration, arg.EventID, arg.UserID)
	return err
}

const getMatchmakingRegistrationsForEvent = `-- name: GetMatchmakingRegistrationsForEvent :many
SELECT r.user_id, r.can_substitute, r.can_lobby_host, r.duo_request, r.created_at,
       u.discord_name,
       gm.game_id,
       ug.avg_rank,
       cr."order" AS current_rank_order,
       pr."order" AS peak_rank_order,
       ar."order" AS avg_rank_order
FROM registrations r
JOIN users u ON u.id = r.user_id
JOIN events e ON e.id = r.event_id
JOIN game_modes gm ON gm.id = e.game_mode_id
JOIN user_games ug ON ug.user_id = r.user_id AND ug.game_id = gm.game_id
JOIN game_ranks cr ON cr.id = ug.current_rank
JOIN game_ranks pr ON pr.id = ug.peak_rank
LEFT JOIN game_ranks ar ON ar.id = ug.avg_rank
WHERE r.event_id = $1
ORDER BY r.created_at ASC
`

type GetMatchmakingRegistrationsForEventRow struct {
	UserID           uuid.UUID
	CanSubstitute    bool
	CanLobbyHost     bool
	DuoRequest       *string
	CreatedAt        time.Time
	DiscordName      *string
	GameID           uuid.UUID
	AvgRank          *uuid.UUID
	CurrentRankOrder int32
	PeakRankOrder    int32
	AvgRankOrder     *int32
}

func (q *Queries) GetMatchmakingRegistrationsForEvent(ctx context.Context, eventID uuid.UUID) ([]GetMatchmakingRegistrationsForEventRow, error) {
	rows, err := q.db.Query(ctx, getMatchmakingRegistrationsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchmakingRegistrationsForEventRow
	for rows.Next() {
		var i GetMatchmakingRegistrationsForEventRow
		if err := rows.Scan(
			&i.UserID,
			&i.CanSubstitute,
			&i.CanLobbyHost,
			&i.DuoRequest,
			&i.CreatedAt,
			&i.DiscordName,
			&i.GameID,
			&i.AvgRank,
			&i.CurrentRankOrder,
			&i.PeakRankOrder,
			&i.AvgRankOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegistrationByEventAndUser = `-- name: GetRegistrationByEventAndUser :one
SELECT event_id, user_id, can_substitute, can_lobby_host, duo_request, created_at, updated_at
FROM registrations
WHERE event_id = $1 AND user_id = $2
`

type GetRegistrationByEventAndUserParams struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetRegistrationByEventAndUser(ctx context.Context, arg GetRegistrationByEventAndUserParams) (Registration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByEventAndUser, arg.EventID, arg.UserID)
	var i Registration
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.CanSubstitute,
		&i.CanLobbyHost,
		&i.DuoRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationDataByEventId = `-- name: GetRegistrationDataByEventId :many
SELECT r.event_id, r.user_id, r.can_substitute, r.can_lobby_host, r.duo_request, r.created_at, r.updated_at, 
    U.discord_name, 
    CASE 
		WHEN $1::BOOL = TRUE OR U.show_pronouns = true THEN COALESCE(U.pronouns, '')
		ELSE ''
	END AS pronouns,
    CASE
        WHEN $1::BOOL = TRUE OR COALESCE(UG.show_rank, FALSE) = TRUE THEN COALESCE(GR.name, '')
        ELSE ''
    END AS current_rank_name,
    CASE
        WHEN $1::BOOL = TRUE OR COALESCE(UG.show_rank, FALSE) = TRUE THEN COALESCE(PR.name, '')
        ELSE ''
    END AS peak_rank_name,
    CASE
        WHEN $1::BOOL = TRUE OR COALESCE(UG.show_rank, FALSE) = TRUE THEN COALESCE(AR.name, '')
        ELSE ''
    END AS avg_rank_name,
    COALESCE(UG.in_game_name, '') AS in_game_name
FROM registrations AS R 
JOIN users AS U ON R.user_id = U.id 
JOIN events AS E ON R.event_id = E.id
JOIN event_groups AS EG ON E.group_id = EG.id
JOIN game_modes AS GM ON GM.id = E.game_mode_id
LEFT JOIN user_games AS UG ON R.user_id = UG.user_id AND UG.game_id = GM.game_id
LEFT JOIN game_ranks AS GR ON UG.current_rank = GR.id
LEFT JOIN game_ranks AS PR ON UG.peak_rank = PR.id
LEFT JOIN game_ranks AS AR ON UG.avg_rank = AR.id
WHERE R.event_id = $2
ORDER BY U.discord_name ASC
`

type GetRegistrationDataByEventIdParams struct {
	ViewerIsHost bool
	EventID      uuid.UUID
}

type GetRegistrationDataByEventIdRow struct {
	EventID         uuid.UUID
	UserID          uuid.UUID
	CanSubstitute   bool
	CanLobbyHost    bool
	DuoRequest      *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DiscordName     *string
	Pronouns        string
	CurrentRankName string
	PeakRankName    string
	AvgRankName     string
	InGameName      string
}

func (q *Queries) GetRegistrationDataByEventId(ctx context.Context, arg GetRegistrationDataByEventIdParams) ([]GetRegistrationDataByEventIdRow, error) {
	rows, err := q.db.Query(ctx, getRegistrationDataByEventId, arg.ViewerIsHost, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRegistrationDataByEventIdRow
	for rows.Next() {
		var i GetRegistrationDataByEventIdRow
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.CanSubstitute,
			&i.CanLobbyHost,
			&i.DuoRequest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DiscordName,
			&i.Pronouns,
			&i.CurrentRankName,
			&i.PeakRankName,
			&i.AvgRankName,
			&i.InGameName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegistrationsForEvent = `-- name: GetRegistrationsForEvent :many
SELECT user_id, can_lobby_host, created_at
FROM registrations
WHERE event_id = $1
ORDER BY created_at ASC
`

type GetRegistrationsForEventRow struct {
	UserID       uuid.UUID
	CanLobbyHost bool
	CreatedAt    time.Time
}

func (q *Queries) GetRegistrationsForEvent(ctx context.Context, eventID uuid.UUID) ([]GetRegistrationsForEventRow, error) {
	rows, err := q.db.Query(ctx, getRegistrationsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRegistrationsForEventRow
	for rows.Next() {
		var i GetRegistrationsForEventRow
		if err := rows.Scan(&i.UserID, &i.CanLobbyHost, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegistration = `-- name: UpdateRegistration :one
UPDATE registrations
SET can_substitute = $3, can_lobby_host = $4, duo_request = $5, updated_at = NOW()
WHERE event_id = $1 AND user_id = $2
RETURNING event_id, user_id, can_substitute, can_lobby_host, duo_request, created_at, updated_at
`

type UpdateRegistrationParams struct {
	EventID       uuid.UUID
	UserID        uuid.UUID
	CanSubstitute bool
	CanLobbyHost  bool
	DuoRequest    *string
}

func (q *Queries) UpdateRegistration(ctx context.Context, arg UpdateRegistrationParams) (Registration, error) {
	row := q.db.QueryRow(ctx, updateRegistration,
		arg.EventID,
		arg.UserID,
		arg.CanSubstitute,
		arg.CanLobbyHost,
		arg.DuoRequest,
	)
	var i Registration
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.CanSubstitute,
		&i.CanLobbyHost,
		&i.DuoRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
