// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRegistrationDataByEventId = `-- name: GetRegistrationDataByEventId :many
SELECT r.event_id, r.user_id, r.can_substitute, r.can_lobby_host, r.duo_request, r.created_at, r.updated_at, 
    U.discord_name, 
    CASE 
		WHEN U.show_pronouns = true THEN pronouns 
		ELSE ''
	END AS pronouns, 
    GR.name AS current_rank_name 
FROM registrations AS R 
JOIN users AS U ON R.user_id = U.id 
JOIN events AS E ON R.event_id = E.id
JOIN event_groups AS EG ON E.group_id = EG.id
JOIN user_games AS UG ON R.user_id = UG.user_id AND EG.game_mode_id = UG.game_id
JOIN game_ranks AS GR ON UG.current_rank = GR.id
WHERE event_id = $1
ORDER BY U.discord_name ASC
`

type GetRegistrationDataByEventIdRow struct {
	EventID         uuid.UUID
	UserID          uuid.UUID
	CanSubstitute   bool
	CanLobbyHost    bool
	DuoRequest      *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DiscordName     *string
	Pronouns        string
	CurrentRankName string
}

func (q *Queries) GetRegistrationDataByEventId(ctx context.Context, eventID uuid.UUID) ([]GetRegistrationDataByEventIdRow, error) {
	rows, err := q.db.Query(ctx, getRegistrationDataByEventId, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRegistrationDataByEventIdRow
	for rows.Next() {
		var i GetRegistrationDataByEventIdRow
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.CanSubstitute,
			&i.CanLobbyHost,
			&i.DuoRequest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DiscordName,
			&i.Pronouns,
			&i.CurrentRankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
