// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, discord_id, discord_name, image_url)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region
`

type CreateUserParams struct {
	DiscordID   *string
	DiscordName *string
	ImageUrl    *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.DiscordID, arg.DiscordName, arg.ImageUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
	)
	return i, err
}

const getUserByDiscordID = `-- name: GetUserByDiscordID :one
SELECT id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region FROM users WHERE discord_id = $1
`

func (q *Queries) GetUserByDiscordID(ctx context.Context, discordID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordID, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region FROM users WHERE discord_name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, discordName *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, discordName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET updated_at = NOW(),
    discord_id = $1,
    discord_name = $2,
    image_url = $3,
    pronouns = $4,
    show_pronouns = $5
WHERE id = $6
RETURNING id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region
`

type UpdateUserParams struct {
	DiscordID    *string
	DiscordName  *string
	ImageUrl     *string
	Pronouns     *string
	ShowPronouns bool
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.DiscordID,
		arg.DiscordName,
		arg.ImageUrl,
		arg.Pronouns,
		arg.ShowPronouns,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
	)
	return i, err
}
