// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_games.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getGamesForUser = `-- name: GetGamesForUser :many
SELECT UG.user_id, UG.game_id, UG.in_game_name, UG.current_rank, UG.peak_rank, UG.show_rank, UG.created_at, UG.updated_at,
       G.name as game_name,
       GR_Current.name AS current_rank_name,
       GR_Peak.name AS peak_rank_name
FROM user_games AS UG
JOIN games AS G ON (UG.game_id = G.id)
JOIN game_ranks AS GR_Current ON (UG.current_rank = GR_Current.id)
JOIN game_ranks AS GR_Peak ON (UG.peak_rank = GR_Peak.id)
WHERE UG.user_id = $1
`

type GetGamesForUserRow struct {
	UserID          uuid.UUID
	GameID          uuid.UUID
	InGameName      string
	CurrentRank     *uuid.UUID
	PeakRank        *uuid.UUID
	ShowRank        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	GameName        string
	CurrentRankName string
	PeakRankName    string
}

func (q *Queries) GetGamesForUser(ctx context.Context, userID uuid.UUID) ([]GetGamesForUserRow, error) {
	rows, err := q.db.Query(ctx, getGamesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGamesForUserRow
	for rows.Next() {
		var i GetGamesForUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.GameID,
			&i.InGameName,
			&i.CurrentRank,
			&i.PeakRank,
			&i.ShowRank,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GameName,
			&i.CurrentRankName,
			&i.PeakRankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
