// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, discord_id, discord_name, image_url, display_name)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region, new_user, display_name
`

type CreateUserParams struct {
	DiscordID   *string
	DiscordName *string
	ImageUrl    *string
	DisplayName *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DiscordID,
		arg.DiscordName,
		arg.ImageUrl,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
		&i.NewUser,
		&i.DisplayName,
	)
	return i, err
}

const getUserByDiscordID = `-- name: GetUserByDiscordID :one
SELECT id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region, new_user, display_name FROM users WHERE discord_id = $1
`

func (q *Queries) GetUserByDiscordID(ctx context.Context, discordID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordID, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
		&i.NewUser,
		&i.DisplayName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region, new_user, display_name FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
		&i.NewUser,
		&i.DisplayName,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region, new_user, display_name FROM users WHERE discord_name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, discordName *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, discordName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
		&i.NewUser,
		&i.DisplayName,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET updated_at = NOW(),
    display_name = $1,
    pronouns = $2,
    show_pronouns = $3,
    region = $4,
    new_user = false
WHERE id = $5
RETURNING id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region, new_user, display_name
`

type UpdateUserParams struct {
	DisplayName  *string
	Pronouns     *string
	ShowPronouns bool
	Region       *string
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.DisplayName,
		arg.Pronouns,
		arg.ShowPronouns,
		arg.Region,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
		&i.NewUser,
		&i.DisplayName,
	)
	return i, err
}

const updateUserFromLogin = `-- name: UpdateUserFromLogin :one
UPDATE users
SET updated_at = NOW(),
    discord_name = $1,
    image_url = $2
WHERE id = $3
RETURNING id, discord_id, discord_name, image_url, pronouns, show_pronouns, created_at, updated_at, region, new_user, display_name
`

type UpdateUserFromLoginParams struct {
	DiscordName *string
	ImageUrl    *string
	ID          uuid.UUID
}

func (q *Queries) UpdateUserFromLogin(ctx context.Context, arg UpdateUserFromLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFromLogin, arg.DiscordName, arg.ImageUrl, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordName,
		&i.ImageUrl,
		&i.Pronouns,
		&i.ShowPronouns,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Region,
		&i.NewUser,
		&i.DisplayName,
	)
	return i, err
}
