name: Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    env:
      COVERAGE_PCT: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: backend/go.sum

      - name: Start Test Database
        working-directory: .
        run: |
          docker compose -f docker-compose.test.yml up -d --wait db-test

      - name: Run Go Tests with Filtered Coverage
        working-directory: ./backend/internal
        env:
          # Database link for your test_util package 
          DATABASE_URL_TESTS: "postgres://testuser:testpass@localhost:54321/matchmaker_test?sslmode=disable"
          
          # Server Config 
          PORT: 8080
          GIN_MODE: release
          
          # Security Keys (Dummy values for testing) 
          COOKIE_HASH_KEY: "12345678901234567890123456789012"
          COOKIE_ENCRYPT_KEY: "12345678901234567890123456789012"
          JWT_SECRET: "12345678901234567890123456789012"
          
          # OAuth & CORS (Not used by unit tests, but required for init) 
          DISCORD_CLIENT_ID: "mock_id"
          DISCORD_CLIENT_SECRET: "mock_secret"
          DISCORD_REDIRECT_URI: "http://localhost:8080/callback"
          FRONTEND_URL: "http://localhost:3000"
        run: |
          PKGS=$(go list ./... | grep -vE "db|test_util")
          go test -p 1 -v -coverprofile=coverage.out $PKGS
          sed -i '/mock_store.go/d' coverage.out
          PCT=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "COVERAGE_PCT=$PCT" >> $GITHUB_ENV
          echo "The captured coverage is: $PCT"
          echo "### Backend Coverage Summary" >> $GITHUB_STEP_SUMMARY
          go tool cover -func=coverage.out >> $GITHUB_STEP_SUMMARY

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: backend/internal/coverage.out
          retention-days: 7

      - name: Update Coverage Badge
        # Only run on main branch so development branches don't overwrite the "official" badge
        if: github.ref == 'refs/heads/main'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: c21c84f4fba3f91f41a5be25dd59326a
          filename: matchmaker-coverage.json
          label: Backend Coverage
          message: ${{ env.COVERAGE_PCT }}%
          valColorRange: ${{ env.COVERAGE_PCT }}
          maxColorRange: 100
          minColorRange: 0

      - name: Stop Test Database
        if: always()
        working-directory: .
        run: docker compose -f docker-compose.test.yml down